# Haoran Yang
## week 10 03/22/2021
### Python_Numpy arrays processing



In [1]:
import numpy as np 

In [2]:
my_lst = [11,22,33,44,55,66,77]

print(my_lst)

[11, 22, 33, 44, 55, 66, 77]


In [4]:
my_arr = np.array(my_lst)

In [5]:
print(my_arr.dtype)

int32


In [6]:
fruits = ['Orange','Apple','Cherry','Pear']

my_strarr = np.array(fruits)

print(my_strarr.dtype)
# uniconde

<U6


In [7]:
my_arr2 = np.array([11,22,33,44,55], dtype='S')

In [8]:
print(my_arr2.dtype)

|S2


In [9]:
# if we chan it to singel number:

In [10]:
my_arr3 = np.array([1,2,3,4,5], dtype='S')

In [12]:
print(my_arr3.dtype)
# it became S1

|S1


In [14]:
my_arr4 = np.array([5,6,7,8,9], dtype = 'i4')

In [15]:
print(my_arr4.dtype)

int32


In [17]:
# example of a error:
# However, professor just found this is new version which means this is not a error for now!
my_errarr = np.array(['1','2','3','4','5'], dtype = 'i')

In [18]:
print(my_errarr)

[1 2 3 4 5]


In [21]:
# Actual error:
my_errarr1 = np.array(['1','2','3','c'],dtype='i')
# c can not be integer elements

ValueError: invalid literal for int() with base 10: 'c'

In [23]:
score = [78.5,99.2,90.3,89.9]

my_arrscore = np.array(score)

In [24]:
print(my_arrscore)

[78.5 99.2 90.3 89.9]


In [25]:
arr = my_arrscore.astype('i')

In [26]:
print(arr)
# Finally we converting the float number to integer.

[78 99 90 89]


In [32]:
# how can we convert integer to boolean? like 0 represent false and other number are true.
arr = np.array([0,0,1,3,4,7,0,])

print(arr.dtype)

int32


In [29]:
bool_arr = arr.astype(bool)

In [34]:
print(arr)
print(bool_arr)
# comparing them....

[0 0 1 3 4 7 0]
[False False  True  True  True  True False]


In [35]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_lst = [lst1,lst2]

my_arr = np.array(my_lst)

print(my_arr)
print(my_arr.ndim)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
2


In [36]:
# Numpy built-in functions to generate arrays from existing arrays 
# copy and view, intead of using '='

my_lst = [11,12,15,14,50]

arr = np.array(my_lst)

c_arr = arr.copy()

print(arr)
print(c_arr)

[11 12 15 14 50]
[11 12 15 14 50]


In [38]:
arr[3] = 4
print(arr)
print(c_arr)
# the copy one is not changed, bcz it is completely seperate.

[11 12 15  4 50]
[11 12 15 14 50]


In [39]:
# View:
my_lst = [11,22,15,14,50]

arr = np.array(my_lst)

c_arr = arr.view()

print(arr)
print(c_arr)

[11 22 15 14 50]
[11 22 15 14 50]


In [41]:
arr[3]=4
print(arr)
print(c_arr)
# For here, view also change.
# if view change, both of them will change

[11 22 15  4 50]
[11 22 15  4 50]


In [ ]:
# shaoe gives the number of elements in each dimentions :

In [44]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_lst = [lst1,lst2]

my_arr = np.array(my_lst)
print(my_arr)
my_arr.shape

# the '2' representing the first dimentio has two elements, and second dimention has 5 elements.

[[ 1  2  3  4  5]
 [11 22 33 44 55]]


(2, 5)

In [46]:
# shape return 2 dimention and each dimention ahs 5 elements:

In [49]:
arr = np.array(lst1, ndmin = 4)
print(arr)
print(arr.ndim)
print(arr.shape)

[[[[1 2 3 4 5]]]]
4
(1, 1, 1, 5)


In [50]:
arr = np.array(lst1, ndmin = 6)
print(arr)
print(arr.ndim) # telling you how many dimention has 
print(arr.shape) # telling you how many elements in each dimentions

[[[[[[1 2 3 4 5]]]]]]
6
(1, 1, 1, 1, 1, 5)


In [ ]:
# each index in the shape tells the number of elements in each dimention....