# Haoran Yang
## Week 10 03/22/2021
### Python - Numpy - introduction


In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [3]:
# Numpy is a open source which likes a python library. 
# There are lots of function (Built in)inside Numpy.
# faster

In [4]:
arr = np.array([1,2,3,4,5,6])

In [5]:
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr1 = np.array((1,2,3,4,5,6))

In [8]:
arr1

array([1, 2, 3, 4, 5, 6])

In [9]:
type(arr1)

numpy.ndarray

In [10]:
# 0-D Arrays
arr2 = np.array(50)

In [11]:
arr2

array(50)

In [12]:
print(arr2)

50


In [13]:
# 1-dimention arrays
arr3 = np.array([1,2,3,4,5,6])
print(arr3)

[1 2 3 4 5 6]


In [14]:
# 2-Dimenton arrays-matrix
arr4 = np.array([[1,2,3,4,5,6],[11,22,33,44,55,66]])
print(arr4)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [15]:
# 3-dimention arrays 
arr5 = np.array([ [[1,2,3],[4,5,6]], [[11,22,33],[44,55,66]] ])
print(arr5)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [16]:
print(arr2.ndim)
# 'ndim' is using for checking dimention of array

0


In [17]:
print(arr3.ndim)

1


In [18]:
print(arr4.ndim)

2


In [19]:
print(arr5.ndim)

3


In [20]:
# Array Indexing
print(arr3)

[1 2 3 4 5 6]


In [21]:
print(arr3[1])
# How to get specific elements using indexing

2


In [22]:
print(arr3[-1])

6


In [23]:
print(arr3[0]+arr3[3])
# give the sum of two elements

5


In [24]:
# Access 2-D arrays 
print(arr4)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [25]:
print(arr4[0,2])
# [0] representing the first matrix

3


In [26]:
print(arr4[1,-1])

66


In [27]:
# Access 3-D Arrays
print(arr5)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [28]:
# how to get 6?
print(arr5[0,1,2])

6


In [29]:
marr = np.array([1,2,3,4,5],ndmin =5)

In [30]:
print(marr)

[[[[[1 2 3 4 5]]]]]


In [31]:
marr.ndim

5

In [32]:
# slicing nmpy arrays
# [start : end ] --- end index is exclded.
# [start : end : step]
# [:end] start is 0
# [start:] end is the length of the array

In [33]:
print(arr3)

[1 2 3 4 5 6]


In [34]:
print(arr3[1:4])
# the result is includes the start index, but exclude the end index

[2 3 4]


In [35]:
print(arr3[3:4])

[4]


In [36]:
# slice elements from the begining to index 3 (not included)
print(arr3[:3])

[1 2 3]


In [37]:
# slice elements from index 3 to end index 1 from the end of the array.
print(arr3[-3:-1])
# here '-1' which is 6 is excluede, always.

[4 5]


In [38]:
print (arr3[1:5:2])

[2 4]


In [39]:
# return every other elements in the entire array:
print(arr3[::2])

[1 3 5]


In [41]:
# Slice 2-D arrays
print(arr4)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [42]:
print(arr4.ndim)

2


In [44]:
# if we want to get 22,33. which is in 2 dimention, so we using 1, and indexing 1-3.  Bcz end index is excluded
# SO:
print(arr4[1,1:3])

[22 33]


In [45]:
print(arr4[0:2])
# will go to both dimention

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [47]:
print(arr4[0:2,3]) 

[ 4 44]
