# Haoran Yang
## week 11 03/29/2021
## Python Numpy Universal Functions

In [1]:
# can save a lot of time
# code are already inside

In [2]:
import numpy as np

In [9]:
arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18,19]

z =[]

for i, j in zip(arr1,arr2):
    z.append(i + j)
  
z

[12, 14, 16, 18, 20, 22, 24, 26, 28]

In [16]:
# zip

fname = ("Alice","Bob","Christy")
lname = ("Charlie","Calrk","Robert")


flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Calrk'), ('Christy', 'Robert'))


In [18]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [19]:
import numpy as np
# just bcz we want rename numpy as np, we can aslo rename it as any other name

In [20]:
arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [21]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [22]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [24]:
# they do not change the array

In [34]:
arr1 = np.random.randn(10)
arr1
# alwasys between -1 and 1 

array([-0.30636615,  0.51340624,  1.37456317, -0.0314277 ,  2.31284846,
       -0.6199082 ,  1.08461581,  0.00913625, -1.01100703,  1.43856546])

In [33]:
arr2 = np.random.randn(10)
arr2

array([ 0.99244288, -1.24073262,  0.35084895, -0.60806846,  0.15372391,
        0.01799882,  0.85504378, -0.55124577,  1.82938667, -0.92254714])

In [35]:
np.add(arr1,arr2)

array([ 0.68607672, -0.72732638,  1.72541211, -0.63949616,  2.46657237,
       -0.60190938,  1.93965959, -0.54210952,  0.81837964,  0.51601831])

In [36]:
np.maximum(arr1,arr2)

array([ 0.99244288,  0.51340624,  1.37456317, -0.0314277 ,  2.31284846,
        0.01799882,  1.08461581,  0.00913625,  1.82938667,  1.43856546])

In [39]:
# np.where
arr = np.arange(9).reshape((3,3))

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [44]:
np.where(arr<4,-1,-2)

array([[-1, -1, -1],
       [-1, -2, -2],
       [-2, -2, -2]])

In [46]:
np.where((arr<4)&(arr>2),-1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [56]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array ([10,20,30,40,50])

arr_b = np.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)

print(list(zip(arr1,arr2,arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]


In [54]:
# using list comprehension 
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]
arr3

[1, 20, 3, 4, 50]

In [58]:
# using np.where

arr3 = np.where(arr_b,arr1,arr2)

arr3

array([ 1, 20,  3,  4, 50])