# Haoran Yang
## week 11 03/29/2021
## Python Numpy Universal Functions

In [1]:
# can save a lot of time
# code are already inside

In [2]:
import numpy as np

In [3]:
arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18,19]

z =[]

for i, j in zip(arr1,arr2):
    z.append(i + j)
  
z

[12, 14, 16, 18, 20, 22, 24, 26, 28]

In [4]:
# zip

fname = ("Alice","Bob","Christy")
lname = ("Charlie","Calrk","Robert")


flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Calrk'), ('Christy', 'Robert'))


In [5]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [6]:
import numpy as np
# just bcz we want rename numpy as np, we can aslo rename it as any other name

In [7]:
arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [8]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [9]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [11]:
# they do not change the array

In [12]:
arr1 = np.random.randn(10)
arr1
# alwasys between -1 and 1 

array([-0.53745877,  0.2695001 , -0.09395284, -1.27526909, -0.20210384,
       -0.36712473,  0.47768835,  0.48669355, -0.52924738,  0.47493589])

In [13]:
arr2 = np.random.randn(10)
arr2

array([-0.75770325,  0.04046867,  0.06532955, -0.69524335,  1.57879522,
        1.25009867, -0.20318393,  0.78979651,  0.63988687,  0.27960093])

In [14]:
np.add(arr1,arr2)

array([-1.29516202,  0.30996877, -0.02862329, -1.97051244,  1.37669138,
        0.88297394,  0.27450443,  1.27649006,  0.1106395 ,  0.75453682])

In [15]:
np.maximum(arr1,arr2)

array([-0.53745877,  0.2695001 ,  0.06532955, -0.69524335,  1.57879522,
        1.25009867,  0.47768835,  0.78979651,  0.63988687,  0.47493589])

In [16]:
# np.where
arr = np.arange(9).reshape((3,3))

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [18]:
np.where(arr<4,-1,-2)

array([[-1, -1, -1],
       [-1, -2, -2],
       [-2, -2, -2]])

In [19]:
np.where((arr<4)&(arr>2),-1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [20]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array ([10,20,30,40,50])

arr_b = np.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)

print(list(zip(arr1,arr2,arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]


In [21]:
# using list comprehension 
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]
arr3

[1, 20, 3, 4, 50]

In [22]:
# using np.where

arr3 = np.where(arr_b,arr1,arr2)

arr3

array([ 1, 20,  3,  4, 50])

In [23]:
### more examples:

In [26]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array ([[5,6],[7,8]])
cond = np.array([[True,False],[True,True]])

np.where(cond,arr1,arr2)

array([[1, 6],
       [3, 4]])

In [28]:
np.where([[True,False],[True,True]],[[5,6],[7,8]],[[1,2],[3,4]])

array([[5, 2],
       [7, 8]])

In [30]:
from numpy.random import randn ### randn will give number between -1 and 1. standard normal distribution
arr = randn(3,3)
arr

array([[ 1.13285986,  0.21798433,  0.78983687],
       [ 0.05190684, -0.3205204 , -0.05162046],
       [ 1.40053407, -0.93298192,  0.78434855]])

In [31]:
np.where(arr<0,0,arr)# understand what happen here.

array([[1.13285986, 0.21798433, 0.78983687],
       [0.05190684, 0.        , 0.        ],
       [1.40053407, 0.        , 0.78434855]])

In [32]:
arr_b = np.array([True,False,True,False,False])
arr_b.any()# hint shift+tab to see what happen here

True

In [34]:
arr_b.all()# this one need all elements are true

False

In [36]:
fruits = np.array(['Apple','Cherry','Apple','Orange','Cherry','Banana'])

np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [38]:
np.in1d(['Apple','Cherry','Grape'],fruits)

array([ True,  True, False])

In [40]:
# Statistical measures.
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
arr


(3, 3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr.sum()

45

In [42]:
arr.sum(0)

array([12, 15, 18])

In [43]:
arr.sum(1)

array([ 6, 15, 24])

In [48]:
arr.sum(2)
# error example 

AxisError: axis 2 is out of bounds for array of dimension 2

In [49]:
print(arr)
np.sum(arr, axis = 0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [50]:
print(arr)
np.sum(arr, axis = 1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ 6, 15, 24])

In [51]:
print(arr)
np.sum(arr, axis = None) # get all sum together 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [52]:
## get the mean:
arr.mean()

5.0

In [54]:
print(arr)
arr.mean(0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4., 5., 6.])

In [56]:
np.mean(arr,axis=0)

array([4., 5., 6.])

In [57]:
np.mean(arr,axis=1)

array([2., 5., 8.])

In [58]:
arr.var()

6.666666666666667

In [59]:
arr.std()# standard deviation

2.581988897471611

In [61]:
arr = np.array([3,6,8,1,9,10,3,5,63,9,12,10,15,11,14])

arr.sort()

arr

array([ 1,  3,  3,  5,  6,  8,  9,  9, 10, 10, 11, 12, 14, 15, 63])

In [62]:
# identity array
i = np.eye(5)

i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
a = np.arange(25).reshape((5,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [66]:
a * i 

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.,  0.],
       [ 0.,  0., 12.,  0.,  0.],
       [ 0.,  0.,  0., 18.,  0.],
       [ 0.,  0.,  0.,  0., 24.]])

In [69]:
i = np.eye(2)
print(i)
a = np.arange(4).reshape((2,2))
print(a)
a*i

[[1. 0.]
 [0. 1.]]
[[0 1]
 [2 3]]


array([[0., 0.],
       [0., 3.]])

In [81]:
m = np.mat([[1,2],[3,4,]])
m

matrix([[1, 2],
        [3, 4]])

In [82]:
m * i

matrix([[1., 2.],
        [3., 4.]])

In [84]:
# Transpose

arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape)
print(arr)
print('-----------------')

t = arr.T


t

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
-----------------


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [85]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [86]:
arr.transpose(0,1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [87]:
arr.transpose(1,0)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [89]:
arr_3d = np.arange(20).reshape((2,5,2))
arr_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [90]:
arr_3d.transpose((0,1,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [91]:
arr_3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [92]:
np.random.random((4,4))

array([[0.55006121, 0.99379786, 0.99596075, 0.28239953],
       [0.45326442, 0.94574427, 0.40256122, 0.92633269],
       [0.36158776, 0.81416858, 0.53929735, 0.71714999],
       [0.04054825, 0.27168131, 0.00149502, 0.65523007]])

In [96]:
from numpy.random import random
random((4,4))

array([[0.18223813, 0.52064886, 0.88362911, 0.19220739],
       [0.23289727, 0.00643927, 0.51974391, 0.31844909],
       [0.99953646, 0.71829989, 0.16220204, 0.88109673],
       [0.19421946, 0.30602913, 0.59476689, 0.55594122]])

In [97]:
from numpy.random import randn
randn(5,5)

array([[ 0.5186025 , -0.55258959,  1.76179249, -0.2464375 ,  1.35819493],
       [-2.4941338 , -0.04271645, -0.68873327, -0.77626608,  1.41469163],
       [ 2.13640737,  1.18859022,  1.22026571, -0.42211097, -0.77598111],
       [ 0.06778892,  1.24099166, -0.72050869, -1.47573789,  0.34921307],
       [-0.48866899,  0.4615552 , -0.42770622,  0.844018  , -0.00637871]])

In [98]:
randn(5)

array([-1.1240763 , -0.28311519, -1.83258479, -0.64832474, -0.49782986])

In [99]:
np.random.randint(10,50)

35

In [105]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True

In [102]:
website

'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'

In [106]:
import pandas as pd 
### pandas is also a opensource library 