# Haoran Yang
## week 11  03/29/2021
### Python_numpy creating, processing, transporting arrays


In [4]:
import numpy as np

arr_2d = np.array([[1,2,3,4],[5,6,7,8]])

print(arr_2d)

print (arr_2d.ndim)

print (arr_2d.shape)

print(arr_2d.dtype)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int32


In [5]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
print(arr.ndim)
arr.dtype

1


dtype('float64')

In [10]:
arr_2d = np.zeros((5,5))

print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2
float64


In [11]:
arr = np.ones((5,5))

print(arr)
print(arr.ndim)
print(arr.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2
float64


In [12]:
arr = np.empty((2,2))

print(arr)
print(arr.ndim)
print(arr.dtype)

[[4.24399158e-314 8.48798317e-314]
 [1.27319747e-313 1.69759663e-313]]
2
float64


In [17]:
arr = np.empty((3,3),dtype = int)

print(arr)
print(arr.ndim)
print(arr.dtype)

[[1183490512      32760          0]
 [         0          0          0]
 [         1         18         24]]
2
int32


In [19]:
# arange 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [28]:
np.arange(10,100,5)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

(18,)
1
int32


In [31]:
arr = np.arange(1,13,1)
print(arr)
print(arr.ndim)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)


In [32]:
# reshape arrays
# 1-D to 2-D
arr_2d = arr.reshape(3,4)

print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
arr_2d = arr.reshape(2,6)

print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [53]:
#  can not bigger than 12 with multiply of (a,b) a*b=12
arr_2d = arr.reshape(2,7)

print(arr_2d)

ValueError: cannot reshape array of size 12 into shape (2,7)

In [43]:
# reshape 1-D to 3-D
arr_3d = arr.reshape(3,2,2)

print(arr_3d)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [52]:
arr_3d = arr.reshape(2,3,2)

print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [49]:
# reshape is a view or copy 
print(arr_2d.base)#---this is not a copy ,is a view 

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [50]:
# unknown dimentions
arr_3d = arr.reshape(2,2,-1)

print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [54]:
# chenge 2-D to 1-D 
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [55]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
# Iterating 1-D 
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [57]:
for n in arr:
    print(n)

0
1
2
3
4
5
6
7
8
9


In [59]:
# for 2-D Iterating 
arr = np.array([[1,2,3,4],[5,6,7,8]])

for n in arr:
    print(n)

[1 2 3 4]
[5 6 7 8]


In [60]:
for n in arr:
    for x in n :
        print(x)

1
2
3
4
5
6
7
8


In [66]:
# Iterating  3-D arrays 
arr_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr_3d)
print(arr_3d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [68]:
for n in arr_3d:
    print(n)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [69]:
for n3 in arr_3d:
    for n2 in n3:
        for n1 in n2:
            print(n1)

1
2
3
4
5
6
7
8
9
10
11
12


In [71]:
# another easier way :
# nditer can iterate on each scalar element in np array:
for n in np.nditer(arr_3d):
    print(n)

1
2
3
4
5
6
7
8
9
10
11
12


In [72]:
arr_2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [73]:
arr_2d[:,::2]
# will skpping one element

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [75]:
for n in np.nditer(arr_2d[:,::2]):
    print(n)

1
3
5
7
9
11


In [77]:
arr = np.arange(1,13,1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [81]:
# index with 1-D
for i, n in np.ndenumerate(arr):
    print(i, n)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10
(10,) 11
(11,) 12


In [84]:
# index with 2-D
arr_2d = np.array([[1,2],[3,4],[5,6],[7,8]])
print(arr_2d.shape)

(4, 2)


In [85]:
for i, v in np.ndenumerate(arr_2d):
    print(i,v)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4
(2, 0) 5
(2, 1) 6
(3, 0) 7
(3, 1) 8


In [86]:
arr_2d

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [87]:
arr_2d*arr_2d

array([[ 1,  4],
       [ 9, 16],
       [25, 36],
       [49, 64]])

In [89]:
arr_2d - arr_2d

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [90]:
arr_2d + arr_2d

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [91]:
arr_2d ** 3

array([[  1,   8],
       [ 27,  64],
       [125, 216],
       [343, 512]], dtype=int32)

In [92]:
1 / arr_2d

array([[1.        , 0.5       ],
       [0.33333333, 0.25      ],
       [0.2       , 0.16666667],
       [0.14285714, 0.125     ]])

In [93]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [94]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [95]:
arr[::3]

array([ 1,  4,  7, 10])

In [96]:
arr[5:]

array([ 6,  7,  8,  9, 10, 11, 12])

In [98]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [99]:
arr[0:6] = 100 

In [100]:
arr

array([100, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12])

In [103]:
import numpy as np

arr_2d = np.array([[5,10,25],[15,10,20],[20,30,25]])

print(arr_2d.shape)
print(arr_2d)

(3, 3)
[[ 5 10 25]
 [15 10 20]
 [20 30 25]]


In [104]:
arr_2d[1]

array([15, 10, 20])

In [105]:
arr_2d[1,0]

15

In [106]:
# Slicing :
arr_2d[:2,1:]

array([[10, 25],
       [10, 20]])

In [107]:
arr_2d[2]

array([20, 30, 25])

In [108]:
arr_2d[2,-1]

25

In [109]:
arr = np.zeros ((9,9))

arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [110]:
arr.shape

(9, 9)

In [111]:
arr.shape[0]

9

In [112]:
arr.shape[1]

9

In [113]:
arr.shape[2]

IndexError: tuple index out of range

In [116]:
l = arr.shape [0]

for idx in range(l):
    arr[idx] = 10 
    
    
arr

array([[10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [117]:
arr[::2,3:6]

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [118]:
arr[[3,5]]

array([[10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [122]:
# reshape:
arr = np.arange(45).reshape (9,5)


# output
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [123]:
arr_t =arr.T

# output
arr_t

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44]])

In [124]:
np.dot(arr_t,arr)

array([[5100, 5280, 5460, 5640, 5820],
       [5280, 5469, 5658, 5847, 6036],
       [5460, 5658, 5856, 6054, 6252],
       [5640, 5847, 6054, 6261, 6468],
       [5820, 6036, 6252, 6468, 6684]])

In [126]:
arr_3d = np.arange(45).reshape(3,5,3)

arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [128]:
# swapaxes 

arr = np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [130]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])